name: Job Bot

on:
  schedule:
    # Run at 11 AM, 2 PM, and 5 PM on Tuesday, Wednesday, Saturday, Sunday (UTC time)
    - cron: '0 15 * * 2'   # 11 AM ET on Tuesday
    - cron: '0 18 * * 2'   # 2 PM ET on Tuesday
    - cron: '0 21 * * 2'   # 5 PM ET on Tuesday
    - cron: '0 15 * * 3'   # 11 AM ET on Wednesday
    - cron: '0 18 * * 3'   # 2 PM ET on Wednesday
    - cron: '0 21 * * 3'   # 5 PM ET on Wednesday
    - cron: '0 15 * * 6'   # 11 AM ET on Saturday
    - cron: '0 18 * * 6'   # 2 PM ET on Saturday
    - cron: '0 21 * * 6'   # 5 PM ET on Saturday
    - cron: '0 15 * * 0'   # 11 AM ET on Sunday
    - cron: '0 18 * * 0'   # 2 PM ET on Sunday
    - cron: '0 21 * * 0'   # 5 PM ET on Sunday
  workflow_dispatch:  

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          test -f requirements.txt && echo "✅ Found requirements.txt" || (echo "❌ Missing requirements.txt" && exit 1)
          pip install -r requirements.txt

      - name: Run the bot
        env:
          COURIER_AUTH_TOKEN: ${{ secrets.COURIER_AUTH_TOKEN }}
          COURIER_EMAIL_TO: ${{ secrets.COURIER_EMAIL_TO }}
          COURIER_TEMPLATE_ID: ${{ secrets.COURIER_TEMPLATE_ID }}
          SERPAPI_API_KEY: ${{ secrets.SERPAPI_API_KEY }}
          OPEN_API_KEY: ${{ secrets.OPEN_API_KEY }} 
        run: python jobscraper.py
